### ISSUE TITLE
Relationship with Beanfield

### ISSUE THREAD

**Issue by darkdrgn2k** [tomeshnet/toronto-community-network#10]
<sup>_This initial comment is collaborative and open to modification by all._</sup>
## Task Summary

🎟️ **Re-ticketed from:** #  
📅 **Due date:** N/A  
🎯 **Success criteria:** Establish an understanding and relationship with beanfield and tomesh

...

## To Do

- [x] Contact Beanfield 
- [x] See if they are willing to donate
- [x] Check for possibility of service at 88 Queens Quay W, 29 floor 
- [x] Initial Ask
- [x] Get Response

**Comment by darkdrgn2k** [comment]
@makeworld-the-better-one:  Why is this blocked?

@TimTor I think you reach out not to long ago, did you hear back?

**Comment by TimTor** [comment]
Yes, we're still in conversation with them about thise, as far as I know.  May I remove the block label @makeworld-the-better-one ?

**Comment by makeworld-the-better-one** [comment]
@TimTor Removed!

**Comment by TimTor** [comment]
Beanfield has requested a 1-pager to circulate internally - deliver by Sept. 28th

**Comment by YurkoWasHere** [comment]
Waiting on cisco for install.

**Comment by YurkoWasHere** [comment]
> Cisco
You need to start your “config” conversation with your Beanfield contacts.  Let them know the install will happen along side ours.
