### ISSUE TITLE
Develop relationship with Parkdale Peoples Economy organization

### ISSUE THREAD

**Issue by ultush** [tomeshnet/toronto-community-network#125]
<sup>_This initial comment is collaborative and open to modification by all._</sup>

## Develop relationship with Parkdale Peoples Economy organization
A network of 30 community organizaitons  ... http://parkdalepeopleseconomy.ca/

🎟️ **Re-ticketed from:** #
📅 **Due date:** March 1, 2021
🎯 **Success criteria:**  Parkdale Peoples Economy agrees to colloborate/partner woth Toronto Mesh
❌ **Blocked by:** 
👈 **Depends on:**  Line of Sight form individuals requiring service, Budget available from Parkdale Peoples Economy

A representative Mercedes Sharpe Zayas) from Parkdale People's Economy contacted Toronto Mesh on Jan 21st to inquire about wifi services for a few members.  A number of options was provided pouliiling potential costs

## To Do
- [ ] Send Response email to Mercedez, representative with Parkdale People's Economy 
- [ ] Plan for Parkdale People's Economy members connecting to Toronto Mesh Super Nodes
- [ ] Develop interest in Parkdale People's Economy members  to  become Toronto Mesh members.

Initial email sento hello@tomesh.net:
From: Mercedes Sharpe Zayas <mzayas@parc.on.ca>
Date: Thu, Jan 21, 2021 at 2:14 PM
Subject: Affordable Internet for Community Project
To: hello@tomesh.net <hello@tomesh.net>

Hello there,

My name is Mercedes and I work for the Parkdale People's Economy! I'm currently supporting a community project supporting a group of racialized women from the neighbourhood with accessing community safety workshops over Zoom and eventually creating a set of zines based on their learnings! We have a small budget for the project, and are hoping to provide them with netbooks and wifi services during the project period (~5-6 months). My friend recommended that I get in touch with you to see if you have any recommendations for affordable internet supports - the women are currently located in different pockets of the City (2 in Parkdale, 1 at Weston-Lawrence, 1 in Davenport, and 1 at St Claire) so trying to think of the best way to support them. My mind jumped to the portable devices, similar to the wifi hotspots the TPL were providing, but I know these can be costly (also connecting with the library to see if they have any extra free devices).

Either way, if you have any recommendations, please let me know! No worries either way.

Take care,

Mercedes

**Comment by ultush** [comment]
Here is my draft response, feel free to add in details and edit
-----------------------------------------------
Hello Mercedez
Thank you for contacting Toronto Mesh. There are indeed a number of options.

First, as you have determined already, the individuals requiring internet access need to obtain internet capable devices such as netbooks.  Our only reccomendation here is to consider different low cost laptop and even desktop options, in addition to netbooks. One local nonprofit supplying used and fairly low cost laptops etc. is Free Geek Toronto https://www.freegeektoronto.org/  Their mission includes computer acrsss and will provide what you need.

Second, we can determine if any of members of your group has a Line of Sight (LOS) to one of our Toronto Mesh supernodes or antennas. Essentially can they "see" the top of one of the buldings we have already installed a supernode on, from their window. Here is a map of current and future supernodes: https://tomesh.net/map/
Here is the list of buildings where we currently have of plan to deploy supernodes:
Supernode 1: Woolner
Supernode 2: Albion
Supernode 3
Supernode 1
Supernode 1
If the individuals requiring internet access have a LOS to one of our existing supernodes, all they need is ~ $100 router to connect their internet capable device to our network.  We can help the individuals determine if they have a LOS from their location to one of your supernodes.

Third, and this is a longer term solution for those individuals who dont have LOS access, is to set up a local node that will enable not only one person, but multiple people in the neighbourhood access internet services. This option requires purchasing the node related equipment, and installing it typically on a rooftop of a building. So we can explore this option when none of the other options dont achieve the desired outcomes.  

Feel free to ask any questions, and let us know how you would like to proceed.

**Comment by darkdrgn2k** [comment]
I would also link this map for proposed nodes  https://tomesh.net/map/?proposed=true . easier then trying to list them
Also note that the highlight are is a guess and it may work further.

RE: $100 router - id make it more general and say $100 worth of equipment, 
(Antennas don't have wifi so you may need antenna + a wifi router unless your going to plug the antenna directly into your device)

**Comment by ultush** [comment]
Revised response
--------------------------
Hello Mercedez
Thank you for contacting Toronto Mesh. There are indeed a number of options.

First, as you have determined already, the individuals requiring internet access need to obtain internet capable devices such as netbooks. Our only recomnendation here is to consider different low cost laptop and even desktop options, in addition to netbooks. One local nonprofit supplying used and fairly low cost laptops etc. is Free Geek Toronto https://www.freegeektoronto.org/ Their mission includes computer across and will provide what you need.

Second, we can determine if any of members of your group has a Line of Sight (LOS) to one of our Toronto Mesh supernodes or antennas. Essentially can they "see" the top of one of the buldings we have already installed a supernode on, from their window. Here is a map of current supernodes: https://tomesh.net/map/, and here is the same map with furutre supernodes: https://tomesh.net/map/?proposed=true 

If the individuals requiring internet access have a LOS to one of our existing supernodes, all they need is ~ $100 of equipment to connect their internet capable device to our network. We can help the individuals determine if they have a LOS from their location to one of your supernodes.

Third, and this is a longer-term solution for those individuals who don't have LOS access, is to set up a local node that will enable not only one person, but multiple people in the neighbourhood access internet services. This option requires purchasing the node related equipment, and installing it typically on a rooftop of a building. So we can explore this option when none of the other options achieve the desired outcomes.

Feel free to ask any questions, and let us know how you would like to proceed.
