### ISSUE TITLE
Prepare for community consultation on ConnectTO to City of Toronto

### ISSUE THREAD

**Issue by ultush** [tomeshnet/toronto-community-network#126]
<sup>_This initial comment is collaborative and open to modification by all._</sup>

## City of Toronto is consulting with the tech community to prepare RFP for ConnectTO pilot. ConnectTO is part of City of Toronto's Digital Access Strategy 

🎟️ **Re-ticketed from:** #
📅 **Due date:** N/A
🎯 **Success criteria:** Ensure Mesh Networking is not foreclosed in RFP process
❌ **Blocked by:** 
👈 **Depends on:**

[MAIN TEXT HERE]

## To Do
1. Write requirements for Mesh Networking to be included in procurement tender
2. Ensure Mesh Networking is not foreclosed in RFP process
3. Keep an eye on RFP dates and schedule

- [ ] ...
Bakground info:
https://youtu.be/30uODBY6qT0?t=34086
This link takes you to the start of the Exec Comm consultation on the 27th about the "affordable internet for all"
See time code: 9:28:00
Link to Executive Committee Item
http://app.toronto.ca/tmmis/viewAgendaItemHistory.do?item=2021.EX20.8

Link to City Council Item:
...

**Comment by darkdrgn2k** [comment]
Seesion Details
http://app.toronto.ca/tmmis/viewAgendaItemHistory.do?item=2021.EX20.8

City council session live stream https://youtu.be/-PeQgT1NyQo?t=16214

Motion mentioning community groups

![image](https://user-images.githubusercontent.com/29005789/107125793-d9d6da00-6879-11eb-9d0c-e5bc54b6cde9.png)

![image](https://user-images.githubusercontent.com/29005789/107125802-e3604200-6879-11eb-8826-8c99f3815b36.png)
