### ISSUE TITLE
Co Deployemnt with CISCO

### ISSUE THREAD

**Issue by YurkoWasHere** [tomeshnet/toronto-community-network#59]
<sup>_This initial comment is collaborative and open to modification by all._</sup>

## Task Summary

🎟️ **Re-ticketed from:** #
📅 **Due date:** N/A
🎯 **Success criteria:**: Prepare list of locations we can co-deploy on.

- Buildings you will be installing antennas on
- Which buildings will have the internet feed
- Which buildings have option of indoor hardware
- Any other notes that may be required
- Dates the install are planned for

## To Do

- [x] Get list from cisco
- [x] Confirm details

**Comment by darkdrgn2k** [comment]
Defined in separate issues - #65 #64 #63 #62 #61
