### ISSUE TITLE
Supernode 2 - Thorncliffe North

### ISSUE THREAD

**Issue by darkdrgn2k** [tomeshnet/toronto-community-network#61]
<sup>_This initial comment is collaborative and open to modification by all._</sup>

## Task Summary

🎟️ **Re-ticketed from:** #
📅 **Due date:** Next 2-3 weeks
🎯 **Success criteria:** Deploy Super Node

Deploy super node along side Cisco

53 Thorncliff Pk - Gateway Node
~~P2P Possibility to Woolner~~

![image](https://user-images.githubusercontent.com/29005789/97095399-d736d880-162c-11eb-8ff8-836336ac9d29.png)

## To Do

-  [x] Design Super Node
-  [x] Pay for Super Node
-  [ ] Deploy Super Node

**Comment by darkdrgn2k** [comment]
## Activity: Build out a super node.

Design the North and South Supernodes. There is a outline of all the buildings in the cluster in the first port. Red building indicated a internet connection that will be available.

Consider

- Which building will be the best location to place our sector antennas.
- How will you get internet to that building
- Where would you put the antennas
- How many antennas would you need 
- Which way are they pointing
- What kind of antennas would you use

Cisco has confirmed that the GATEWAY buildings (nodes that have internet access) will have an indoor room to mount and run gear from.  Other buildings may not! There WILL be access to power (POE or Other)

We will present and review the antennas next week at the Network Meeting.

**Comment by makeworld-the-better-one** [comment]
Meeting on 2020-08-13 we decided:
- Put two antennas on 75, pointing east and west
- A south pointing antenna would be put up at a later date on 47, getting Internet from:
	- A PtP link to 53 or
	- The sector already on 47
- Once that is set up, there could be another PtP from 75 to 53 for internet redundancy

**Comment by darkdrgn2k** [comment]
![image](https://user-images.githubusercontent.com/29005789/90278235-124eab80-de35-11ea-943d-b24b96cd0467.png)

**Comment by darkdrgn2k** [comment]
4x [LAP-120](https://www.cdw.com/product/ubiquiti-liteap-lap-120-wireless-bridge/5275702?enkwrd=LAP-120) $90
4x [LBE AC5](https://www.cdw.ca/product/ubiquiti-litebeam-ac-lbe-5ac-gen2-wireless-bridge/4625131?pfm=srh) $86
3x [EdgeRoute X SFP)(https://www.cdw.com/product/ubiquiti-edgerouter-x-sfp-router-desktop/3824301?pfm=srh) $110
1x [ToughCable](https://www.cdw.com/product/ubiquiti-toughcable-pro-bulk-cable-1000-ft-black/3087869?pfm=srh)  $163

**Comment by darkdrgn2k** [comment]
https://tomesh.net/map/?nodeURL=https://raw.githubusercontent.com/tomeshnet/node-list/SN-thorncliff/nodeList.json&proposed=true&buildings=true

node-list - Proposed Deployment

**Comment by darkdrgn2k** [comment]
@infectedroot  can you see if you can get a quote for the hardware listed here

https://github.com/tomeshnet/toronto-community-network/issues/61#issuecomment-674203084

**Comment by infectedroot** [comment]
Pinged my people - I'll let you know the pricing once I get it.

**Comment by darkdrgn2k** [comment]
North side of thorncliffe is no longer viabe

only two buildings will be in south side.
