### ISSUE TITLE
Docs CI improvements

### ISSUE THREAD

**Issue by makeworld-the-better-one** [tomeshnet/toronto-community-network#71]
<sup>_This initial comment is collaborative and open to modification by all._</sup>

## Task Summary

🎟️ **Re-ticketed from:** N/A
📅 **Due date:** N/A
🎯 **Success criteria:** Get the software mentioned below working the CI pipeline, and then merged to master.

## Software
- [x] Spellcheck
	- ~~Maybe https://github.com/lukeapage/node-markdown-spellcheck ?~~
	- [Vale](https://docs.errata.ai/vale/about), maybe with [Github Action](https://github.com/errata-ai/vale-action) for PR support
- [x] Table of contents
	- Automatic: https://github.com/JorelAli/mdBook-pagetoc
	- ~~Have to decide whether to have TOC per page: https://github.com/badboy/mdbook-toc~~
- [x] Link checking
	- https://github.com/Michael-F-Bryan/mdbook-linkcheck

Work is happening in the `ci-71` [branch](https://github.com/tomeshnet/toronto-community-network-docs/tree/ci-71).

## Todo
- [x] Test
- [x] Merge

**Comment by makeworld-the-better-one** [comment]
First real world usage of Vale can be seen [here](https://github.com/tomeshnet/toronto-community-network-docs/pull/4/files).

- `write-good.Passive` should be disabled
- Maybe also `write-good.TooWordy` and `write-good.Weasel`

**Comment by makeworld-the-better-one** [comment]
Note custom wordlists (called "Vocab") doesn't work with Vale yet, see [this comment](https://github.com/tomeshnet/toronto-community-network-docs/pull/3#issuecomment-672129204):

> The [accept and reject files](https://github.com/tomeshnet/toronto-community-network-docs/tree/ci-71/ci/vale/styles/Vocab/main?rgh-link-date=2020-08-11T17%3A46%3A24Z) I added aren't actually being used by Vale, because [that feature](https://docs.errata.ai/vale/vocab) was only introduced in v2.3.0, while the Github Action use v2.2.0. I've opened [an issue](https://github.com/errata-ai/vale-action/issues/20) for this. I think Vale can still be useful, but it may flag our technical words like `babeld` and `supernode`.

**Comment by benhylau** [comment]
Commented on PR that we should keep `Passive` and disable the other two.
