### ISSUE TITLE
Work from heights training

### ISSUE THREAD

**Issue by darkdrgn2k** [tomeshnet/toronto-community-network#72]
<sup>_This initial comment is collaborative and open to modification by all._</sup>

## Task Summary

🎟️ **Re-ticketed from:** #
📅 **Due date:** Next Supernode install date
🎯 **Success criteria:** Member completed the necessary work from height training and is ready to mount equipment.

An Employee Health and Safety (EHS) issue was identified  working on rooftops outside of the “protected” area. This work requires work from heights training and equipment in certain conditions.  
 
Only a few people really need the training.  The person dragging the equipment closer to the edge of the building would 100% require it, but the rest of the people could work in the “protected” area.   

## To Do

- [x] Research how training is delivered
- [x] Look into any "equipment" that may be needed
- [x] Attend training

**Comment by darkdrgn2k** [comment]
One option that was provided to use is using CARAHS (carahs.org)

Located in Pickering just south of the 401 off the Brock rd exit.  Class times start at 7:45am until about 3:30pm. They are limiting class size to 10 people doe to COVID-19

Seems they have classes Wed Aug 12 2020 and Wed Aug 19 2020. Full day seats are $149.00 +HST per person.

Training is valid for 3 years.

1.866.366.2930.

**Comment by darkdrgn2k** [comment]
WHT is required if you are in an area with a meter 3 fall without a railing period.

But harnesses are NOT required if you within 2 meters of the edge.

**Comment by benhylau** [comment]
@TimTor @Pedro-on-a-bike @YurkoWasHere @kaechele how does this look?

---

Toronto Mesh is planning to allocate part of our grant funding to train 2 members for working at heights, from a provider approved by the Chief Prevention Officer (CPO). The training is valid for 3 years, after which the member may take a refresher to get extend the validity, but that falls outside the scope of our sponsorship and the member is under no obligation to extend it.

The expectation is that the certified members will be actively involved and be available for some of our Toronto Community Network supernode deployments, and help ensure deployments are carried out safely for themselves and other members at deployment events. Having the certification does not, however, place them in a position of legal liability for the safety of other members. Members are independently responsible for their own safety.

You can find more information about the training [here](https://www.ontario.ca/page/training-working-heights) and an approved provider from [this list](https://www.ontario.ca/page/training-working-heights#section-1). Trainings are generally one-day, and the top of the list has blended sessions that consists of a 4.5h virtual + 3.5h in-person component. For example, the blended sessions by [4S](https://www.4sconsult.com/blended-working-at-heights-training/) and [4 YOUR SAFETY](https://www.4yoursafety.ca/booking).

You are free to select an approved provider near you. Toronto Mesh will cover up to CAD 170 + tax upon completion, provided that the member:

- has passed the training
- provide a copy (digital) of the receipt of the training
- provide a copy (digital) of the [proof of training](https://www.ontario.ca/page/training-working-heights#proof)
- agree to work with our collaborators to verify their training record upon request

Please remember to take COVID-19 precautions and call the provider first to ensure training schedules during the pandemic.

**Comment by TimTor** [comment]
I suggest change: "allocate part of our grant funding to..." to "allocate funding to" - both to allow for alternative possibilities and securing agreement with partners - for instance, I've been hoping to find people or groups who would sponsor this specifically - and also, we need to validate such an approach with ISOC/FGT.

**Comment by darkdrgn2k** [comment]
Equipment (Source [O. REG 213/91](https://www.ontario.ca/laws/regulation/910213))

From the sounds of things we would need the following:

### BUMP LINE (O. Reg. 213/91, s. 207 (2))

Summary: A perimeter setup to create a SAFE working area for members that would be limited to without WFH training, or additional gear.

![image](https://user-images.githubusercontent.com/29005789/91579659-f3aee100-e919-11ea-9f46-2f12dd3db3bf.png)


#### Required Equipment

- Weighted posts 
- Length of Chain, Cable or Rope to encompass area
- Ability to run the cable around the posts at a height of 0.9m -1.1m

#### Description
> A minimum distance of 2 metres (6 ft 6 in.) is required to set up the signs or bump lines from the unprotected edge. 
Warning barriers have to be 1.1 metres (3 ft 7 in.) in height. They must be made of weighted cables, ropes, posts, or taut chains and have signs or flag warnings along the entirety of its length.
 
> A worker can work inside without additional fall protection measures if the work area is securely installed and maintained with warning signs, warning barriers, and/or bump lines. However, if the worker is working less than 2 metres (6 ft 6 in) from the unprotected edge outside the area, then they must use fall protection or a method of fall arrest. If work is required beyond the warning barrier, travel restraint system or a fall arrest system is required. Lifelines must not be fixed to a bump line or a type of warning method. 

O. REG.
> Roofing

> 207. (1) If a built-up roof is being constructed, repaired or resurfaced, a barrier shall be placed in the immediate work area at least two metres from the perimeter of the roof. O. Reg. 213/91, s. 207 (1).

> (2) The barrier shall consist of portable weighted posts supporting a taut chain, cable or rope that is located 1.1 metres above the roof level. O. Reg. 213/91, s. 207 (2).

### Travel Restraint System (O.Regs 26.4 (1))

Summary: Travel Restrain System prevent the user to step into an unsafe area (ie step off the roof).

#### Description

 
> A travel restraint system is an assembly of components that restricts the movements of a worker to a safe work distance from the edge. It is a fall prevention method and cannot be used as a fall-arrest. This system is required when workers are at a potential danger of falling along a certain distance and the implementation of a guardrail is not practical to provide safety. 

> A travel restraint system is required if work must be completed within 2 metres from an unprotected, and open edge. Areas that cannot be serviced by a travel restraint must be barricaded with bump lines and warning barriers. A competent individual will inspect the travel restraint before every use and any defective component found must be immediately removed.

> Component Selection: Lifelines and/or lanyards must support workers from fall hazards. For example, an adequate lifeline and/or lanyard that meets the requirements of fall protection in one part does not necessarily provide support in another. The lifeline can be too long.
 
> Anchor points: It must be located at the center of the work area and form a right angle to the unprotected edge. 
 
> Identification of fall hazards: The proposed work area must be mapped out for actual and potential fall hazards. Fall hazard information in the proposed work area must be checked for areas around corners, floor openings, and irregularly shaped perimeters. 

> The D-Ring must connect an adequately anchored lifeline to the full body harness worn by the worker. The length of the lifeline to the anchor point must be short enough to restrain a worker from a fall hazard. The lanyard is not used.

> The rope grab, adequately anchored to the lifeline connects the lanyard to the full body harness with a D-ring. A knot in the lifeline or similar mechanism must be there to prevent the rope grab from sliding the length of the lifeline. Otherwise, the restraint becomes ineffective in preventing a fall. 
 
> In both situations, the travel restraint system must be constructed in such a way that the anchor is securely fastened and the lifeline and/or lanyard prevents the worker from falling at any point of its length.

![image](https://user-images.githubusercontent.com/29005789/91579488-b34f6300-e919-11ea-83d2-9a6292dba150.png)



#### Standards 
CAN/CSA-Z259.1-05 Body Belts and Saddles for Work Positioning and Travel Restraint
CAN/CSA-Z259.10-06 Full Body Harnesses

#### O. Regs.
> 26.4 (1) A travel restraint system shall consist of a full body harness with adequate attachment points or a safety belt. O. Reg. 145/00, s. 14.

>  (2) The full body harness or safety belt shall be attached by a lifeline or lanyard to a fixed support that meets the requirements of section 26.7. O. Reg. 145/00, s. 14.

>  (3) The travel restraint system shall be inspected by a competent worker before each use. O. Reg. 145/00, s. 14.

>  (4) If a component of the travel restraint system is found to be defective on inspection, the defective component shall immediately be taken out of service. O. Reg. 145/00, s. 14.


### Fall arrest system

No applicable. Most anchors are on ground level and would exceed the maximum fall of 10ft? before they are engaged. Fall arrest systems require anchors at higher levels.
 
![image](https://user-images.githubusercontent.com/29005789/91579528-c2ceac00-e919-11ea-9083-5c850c32442a.png)

**Comment by darkdrgn2k** [comment]
@Pedro-on-a-bike you mentioned there may be CSA standards for the Bump Line (specifically), Could you look into it.

I know allot of the CSA-Z259 is for GEAR but not the bump line.

**Comment by benhylau** [comment]
I am waiting on confirmation that we have received the ISOC grant to confirm reimbursements.

**Comment by benhylau** [comment]
Operations meeting:
- we are drafting the purchase in a spreadsheet 
- @TimTor will buy these, then reimburse
- approx. $400 + tax in total

**Comment by benhylau** [comment]
This was recommended to me by someone who owns a hardware shop, pls have a look:

- https://www.rona.ca/en/norguard-roofers-kit-medium-large-nrk-200s-50-59025000?viewStore=55070&cq_src=google_ads&cq_cmp=9897044398&cq_con=101247314340&cq_term=&cq_med=&cq_plac=&cq_net=u&cq_pos=&cq_plt=gp&&cm_mmc=shopping_google-_-9897044398-_-101247314340-_-pla-565379815352&gclid=Cj0KCQiAh4j-BRCsARIsAGeV12BDkwB7SlXKXE90yG__mQg8w8QfcaRwDWzZC5XJOOMo9drBb51iCpcaAgvfEALw_wcB&gclsrc=aw.ds
- https://www.norguard.com/component/hikashop/product/11429-ad-rope-grab

>The kits are available from a dozen sources and are designed to save the life of a properly trained worker in a fall while tied-off to a  5000 lb rated anchor point (which ironically doesn’t exist unless the building was designed for window washers). If the fall arrest system is used it typically is accepted for both horizontal travel as well as the higher risk vertical fall risk. There is no one solution and regardless of the amount of gear someone has, no one system is fool proof. For example if someone has to unhook for any reason such as to change anchor points or leapfrog over another worker sharing the same lifeline, Ontario construction law requires a second lanyard to ensure 100%  tie-off at all times.

**Comment by darkdrgn2k** [comment]
For Reference here are the important CSA standards

Canadian Standards Association (CSA) Standards:
The following are the CSA (Canadian Standards Association) standards related to working at Heights:
CAN/CSA-Z259.1-05: Body Belts and Saddles for Work Positioning and Travel Restraint.
CAN/CSE-Z259.2.5-12 (R2016): Fall Arresters and Vertical Lifelines.
CAN/CSA-Z259.2.2-98 (R2004): Self-Retracting Devices for Personal Fall-Arrest Systems.
CAN/CSA-Z259.2.3-99 (R2004): Descent Control Devices.
CAN/CSA-Z259.10-06: Full Body Harnesses.
CAN/CSA-Z259.11-05: Energy Absorbers and Lanyards.
CAN/CSA-Z259.12-01 (R2006): Connecting Components for Personal Fall Arrest Systems (PFAS).
CAN/CSA-Z259.14-01 (R2007): Fall Restrict Equipment for Wood Pole Climbing.

**Comment by benhylau** [comment]
List of materials we are looking into:
- [Harness](https://safetysuppliescanada.com/fall-arrest-harnesses/dynamic-x-style-dyna-2-cross-chest-fall-arrest-harnesses-4d/) $130
- [Rope grab](https://safetysuppliescanada.com/fall-arrest-rope-grabs/automatic-rope-grab-30-e4-dynamic/) $86
- [Rope](https://safetysuppliescanada.com/march-sale/co-polymer-prosteel-rope-w-double-lock-snap-hook-end-uv-resistant-norguard/) $70
- [Locking Snap Hook](https://safetysuppliescanada.com/fall-arrest-harnesses/dynamic-carabiner-double-locking-high-performance-rebar-snap-hook/) $31
- [RONA kit](https://www.rona.ca/en/norguard-roofers-kit-medium-large-nrk-200s-50-59025000?viewStore=55070&cq_src=google_ads&cq_cmp=9897044398&cq_con=101247314340&cq_term=&cq_med=&cq_plac=&cq_net=u&cq_pos=&cq_plt=gp&&cm_mmc=shopping_google-_-9897044398-_-101247314340-_-pla-565379815352&gclid=Cj0KCQiAzZL-BRDnARIsAPCJs73RJhJtkuTC05eXBEXwoaPP0Y3dbnnh-e7ea9VkoBqB30V5rimOXV0aAltcEALw_wcB&gclsrc=aw.ds) $159
- Another lanyard w/o shock absorber
- XL size of harness or belt

**Comment by darkdrgn2k** [comment]
RE Knots

[O. Reg. 213/91](https://www.ontario.ca/laws/regulation/910213)
Section 26.9 (5)

> A horizontal or vertical lifeline shall be kept free from splices or knots, except knots used to connect it to a fixed support. O. Reg. 145/00, s. 14.

**Comment by benhylau** [comment]
@Pedro-on-a-bike @TimTor can you both [upload receipts here](https://cloud.tomesh.net/apps/files/?dir=/tomeshnet-trusted/Receipts&fileid=6215) and fill the expense form? I imagine it can be mixed in with other items that need expensing if you have purchased eligible items in scope for ISOC grant. Thanks.

**Comment by Pedro-on-a-bike** [comment]
Hello,

I've already filled out the expense form and received back from Ryan so
everything is good on my end.

Let me know if there is anything else or missing.

Thanks,
