### ISSUE TITLE
Communications Management System

### ISSUE THREAD

**Issue by Shrinks99** [tomeshnet/toronto-community-network#82]
<sup>_This initial comment is collaborative and open to modification by all._</sup>

## Task Summary

🎟️ **Re-ticketed from:** #
📅 **Due date:** N/A
🎯 **Success criteria:** Set up a system to manage our communications

- Will need to be private
- Is a dedicated CRM needed or can we just use a markdown file?

## To Do

- [x] Research different CRM solutions, figure out if we actually need one
- [x] Set up CRM spreadsheet on the Nextcloud
  - Use @ultush's example spreadsheet as a template for now

**Comment by benhylau** [comment]
Perhaps NextCloud as doc management + a spreadsheet as CRM? We can then also move our calendar to that, from Google Calendar.

**Comment by Shrinks99** [comment]
Last time we used Nextcloud for multi-user editing in the browser it was a bit of a disaster.  Has that been fixed?

**Comment by infectedroot** [comment]
Has anyone used OnlyOffice Community Server?

https://github.com/ONLYOFFICE/CommunityServer

**Comment by benhylau** [comment]
Some new updates just an hour ago re: this https://github.com/hyphacoop/organizing/issues/239#issuecomment-627196214 and I left a note there. If you guys want the full convo on CommunityServer hop onto `#otwsu:matrix.org` we are just having a big discussion about it.

**Comment by benhylau** [comment]
Shall we try NextCloud + OnlyOffice? We will need the CalDAV Calendar on there as well, and an offsite backup.

@infectedroot would you be able to spin this up on same servers since you're already doing the bitwarden?

I think long-term we can move these over to our own infra, and have you and a couple others co-maintain it, and offsite backup to some of our own infra. Thoughts on this plan?

**Comment by infectedroot** [comment]
Totally don't mind. I've setup NextCloud at https://cloud.tomesh.net. Yurko, Tim, and Elon have accounts created and setting up things. I assume it's only a matter of time before there are others on there. Do we still want to play with OnlyOffice?

FYI - the host NextCloud is on has a 32GB HDD... once the drive starts filling up I'll expand it to something like 250-300GBs.

Funny you ask about the long term plan - it crossed my mind today as well. Right now, we're running our internal systems on our own infra, which is OK, but eventually we'll need a proper hosting provider.

I'm totally on board for helping determine what's the most cost-effective provider for us once we really have some traction on the project to gauge proper resourcing requirements.

**Comment by darkdrgn2k** [comment]
#33 
We may also use this deployment to host other services as well

**Comment by benhylau** [comment]
Thanks so much for getting this set up so quick all of you! I have set up my account following the invite. I have two observations:

1. The server seems really slow compared to my two other NextCloud instances, can we check stats to see if it's under stress, particularly CPU, RAM, and bandwidth? Pages take more than one minute to load at times, when I first logged in I refreshed the screen twice thinking it was broken. The console has a bunch of errors and warnings, but I see the same in another instance that I have, and things eventually loaded on here. I wonder if others are experiencing this.

2. I see the ONLYOFFICE here is 5.4.2, that means it may have the issues we saw in 5.5.1 https://github.com/hyphacoop/organizing/issues/239#issuecomment-627196214

    ![Screen Shot 2020-08-19 at 11 21 46 AM](https://user-images.githubusercontent.com/2261308/90618198-ed30b300-e20f-11ea-98a6-55906624cda7.png)

    The latest seems to be [5.6.3](https://www.onlyoffice.com/download.aspx?utm_source=github&utm_medium=cpc&utm_campaign=GitHubCS), which an instance managed by Webarchitects is running. I wonder if the way we deploy can use this version or it is a different packaging and we basically need to wait for it :)

    ![Screen Shot 2020-08-19 at 11 43 24 AM](https://user-images.githubusercontent.com/2261308/90619218-3e8d7200-e211-11ea-85b1-b91c3510d806.png)

>I'm totally on board for helping determine what's the most cost-effective provider for us once we really have some traction on the project to gauge proper resourcing requirements.

That's really great! Toronto Mesh infra has so far been maintained by @darkdrgn2k and @ASoTNetworks. I think we are at the scale where now where we definitely need more devops/sysadmin decentralization!

I think a viable future model is to run these on servers @darkdrgn2k mentioned in #33 or elsewhere, and use home labs as backup systems (e.g. the encrypted bitwarden vault, periodic dump of the NextCloud VM, etc.)

**Comment by darkdrgn2k** [comment]
The way only office was isntalled in NextCloud differs from what web architects use.

In the past it required a docker instance to be run.

New way is integrated right into NextCloud using "Community Document Server". Therefore we don't control the version. But this also means the integration may work better.

I can confirm the version of nextcloud im running has the same version installed.

**Comment by benhylau** [comment]
@Shrinks99 I did this task
> Set up CRM spreadsheet on the Nextcloud 

here https://cloud.tomesh.net/apps/onlyoffice/5150?filePath=%2Ftomeshnet-trusted%2Fcontact-management.xlsx
